name: AleBuild
version: 1.0
main: it.aleemayayt.alebuild.AleBuild
description: Impedisci ai tuoi staffer di rompere i blocchi e rovinare la lobby per sbaglio!
api-version: 1.20
commands:
  build:
    description: Permette di abilitare o disabilitare la possibilità di rompere o piazzare blocchi
    usage: /build
permissions:
  alebuild.build:
    description: Permesso per usare il comando /build
    default: op